[package]
name = "healthcheck_bin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "healthcheck"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
